name: subsynic
description: Sync a self-hosted Subsonic library (metadata + Ogg/Opus downloads) for offline browsing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hooks_riverpod: 3.3.2
  riverpod_annotation: 4.0.3
  flutter_hooks: ^0.21.3
  drift: ^2.34.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  fast_immutable_collections: ^11.2.0
  dio: ^5.11.0
  xml: ^7.0.1
  crypto: ^3.0.7
  auto_route: ^11.1.0
  flutter_taglib: ^1.5.2
  file_picker: ^11.0.3
  saf: ^2.1.0
  path: ^1.9.1
  path_provider: ^2.1.6
  collection: ^1.19.1
  pool: ^1.5.2
  logging: ^1.3.0
  infinite_scroll_pagination: ^5.1.1
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.15.1
  riverpod_generator: 4.0.4
  freezed: 3.2.6-dev.1
  auto_route_generator: ^10.6.0
  drift_dev: 2.34.0
  json_serializable: ^6.14.1
  sqlite3: ^3.5.1

dependency_overrides:
  meta: 1.18.3

flutter:
  uses-material-design: true

  assets:
    - assets/fallback.png
